"""
catalogue.py
========================================================================
SQLite-backed catalogue that tracks speakers across sessions.

The key challenge with pyannote is that it assigns *ephemeral* IDs
(SPEAKER_00, SPEAKER_01 …) that reset with every file. This catalogue
separates ephemeral IDs from stable catalogue IDs, letting you:

  • Map ephemeral IDs → named speaker profiles after human review
  • Track appearance history, speaking time, and sentiment across sources
  • Query by name, affiliation, role, or source
"""

from __future__ import annotations

import json
import logging
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

log = logging.getLogger(__name__)

DEFAULT_DB = Path(__file__).parent / "db" / "speakers.db"


# ======================================================================
# Speaker profile
# ======================================================================
@dataclass
class SpeakerProfile:
    """
    Represents a speaker profile in the catalogue.

    catalogue_id (str):
        Unique stable ID for this speaker (e.g. "SPK-0001").
        Not generated by pyannote.
    display_name (Optional[str]):
        Display name of the speaker (e.g. "John Doe", "Jane Smith" …)
    affiliation (Optional[str]):
        Affiliation of the speaker (e.g. "BBC News", "Labour Party" …)
    role (Optional[str]):
        Role of the speaker (e.g. "Reporter", "MP", "Analyst" …)
    notes (Optional[str]):
        Additional notes about the speaker
    first_seen (str):
        Timestamp of the first appearance of the speaker (ISO-8601)
    last_seen (str):
        Timestamp of the last appearance of the speaker (ISO-8601)
    total_appearances (int):
        Total number of appearances of the speaker
    total_speaking_time (float):
        Total speaking time of the speaker (seconds)
    """
    catalogue_id: str
    display_name: Optional[str]
    affiliation: Optional[str]
    role: Optional[str]
    notes: Optional[str]
    first_seen: str
    last_seen: str
    total_appearances: int
    total_speaking_time: float


class SpeakerCatalogue:
    """
    Persistent store for speaker profiles and session history.
    
    This class manages a SQLite database with three tables:
    1. speakers: Stores speaker profiles with stable catalogue IDs and
       metadata.
    2. sessions: Stores diarization session metadata and the full result
       JSON.
    3. appearances: Links ephemeral speaker IDs from sessions to
       catalogue IDs, along with stats like speaking time and sentiment.
    """

    def __init__(self, db_path: str | Path = DEFAULT_DB):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _init_db(self) -> None:
        with self._conn() as cx:
            cx.executescript("""
            CREATE TABLE IF NOT EXISTS speakers (
                catalogue_id         TEXT PRIMARY KEY,
                display_name         TEXT,
                affiliation          TEXT,
                role                 TEXT,
                notes                TEXT,
                first_seen           TEXT NOT NULL,
                last_seen            TEXT NOT NULL,
                total_appearances    INTEGER NOT NULL DEFAULT 0,
                total_speaking_time  REAL    NOT NULL DEFAULT 0.0
            );

            CREATE TABLE IF NOT EXISTS sessions (
                session_id        TEXT PRIMARY KEY,
                source_name       TEXT,
                source_file       TEXT,
                processed_at      TEXT NOT NULL,
                total_duration    REAL,
                num_speakers      INTEGER,
                result_json       TEXT,    -- full DiarizationResult blob
                broadcast_date    TEXT,
                broadcast_channel TEXT
            );

            CREATE TABLE IF NOT EXISTS appearances (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                catalogue_id    TEXT NOT NULL REFERENCES speakers(catalogue_id),
                session_id      TEXT NOT NULL REFERENCES sessions(session_id),
                ephemeral_id    TEXT NOT NULL,      -- e.g. SPEAKER_00
                source_name     TEXT,
                appeared_at     TEXT NOT NULL,
                speaking_time   REAL    NOT NULL DEFAULT 0.0,
                turn_count      INTEGER NOT NULL DEFAULT 0,
                avg_sentiment   REAL
            );

            CREATE INDEX IF NOT EXISTS idx_app_cat ON appearances(catalogue_id);
            CREATE INDEX IF NOT EXISTS idx_app_ses ON appearances(session_id);

            CREATE TABLE IF NOT EXISTS turn_overrides (
                id               INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id       TEXT    NOT NULL REFERENCES sessions(session_id),
                turn_index       INTEGER NOT NULL,
                original_speaker TEXT    NOT NULL,
                assigned_speaker TEXT    NOT NULL,
                override_at      TEXT    NOT NULL,
                notes            TEXT,
                UNIQUE(session_id, turn_index)
            );
            CREATE INDEX IF NOT EXISTS idx_ovr_ses ON turn_overrides(session_id);
            """)

    def _conn(self) -> sqlite3.Connection:
        cx = sqlite3.connect(str(self.db_path))
        cx.row_factory = sqlite3.Row
        return cx

    # ── Sessions ───────────────────────────────────────────────────────────

    def record_session(self, result) -> str:
        """
        Persist a DiarizationResult. Returns the generated session_id.
        Call this immediately after processing a file; link speakers later.
        """
        session_id = (
            f"{Path(result.source_file).stem}_"
            f"{result.processed_at[:19].replace(':', '-')}"
        )
        with self._conn() as cx:
            cx.execute("""
                INSERT OR REPLACE INTO sessions
                    (session_id, source_name, source_file, processed_at,
                     total_duration, num_speakers, result_json)
                VALUES (?,?,?,?,?,?,?)
            """, (
                session_id,
                result.source_name,
                result.source_file,
                result.processed_at,
                result.total_duration,
                result.num_speakers,
                result.to_json(),
            ))
        log.info(f"Session recorded: {session_id}")
        return session_id

    def list_sessions(self) -> list[dict]:
        with self._conn() as cx:
            rows = cx.execute("""
                SELECT session_id, source_name, processed_at,
                       total_duration, num_speakers,
                       broadcast_date, broadcast_channel
                FROM sessions ORDER BY processed_at DESC
            """).fetchall()
        return [dict(r) for r in rows]

    def update_session_meta(self, session_id: str, source_name: str | None,
                            broadcast_date: str | None, broadcast_channel: str | None):
        with self._conn() as cx:
            cx.execute("""
                UPDATE sessions
                SET source_name = ?, broadcast_date = ?, broadcast_channel = ?
                WHERE session_id = ?
            """, (source_name, broadcast_date, broadcast_channel, session_id))

    # ── Speaker management ─────────────────────────────────────────────────

    def add_speaker(
        self,
        display_name: Optional[str] = None,
        affiliation: Optional[str] = None,
        role: Optional[str] = None,
        notes: Optional[str] = None,
        catalogue_id: Optional[str] = None,
    ) -> str:
        """Register a new speaker. Returns the catalogue_id."""
        if catalogue_id is None:
            catalogue_id = self._next_id()
        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as cx:
            cx.execute("""
                INSERT INTO speakers
                    (catalogue_id, display_name, affiliation, role, notes,
                     first_seen, last_seen)
                VALUES (?,?,?,?,?,?,?)
            """, (catalogue_id, display_name, affiliation, role, notes, now, now))
        log.info(f"Speaker added: {catalogue_id} ({display_name})")
        return catalogue_id

    def update_speaker(self, catalogue_id: str, **fields) -> None:
        """Update any of: display_name, affiliation, role, notes."""
        allowed = {"display_name", "affiliation", "role", "notes"}
        updates = {k: v for k, v in fields.items() if k in allowed}
        if not updates:
            return
        clause = ", ".join(f"{k}=?" for k in updates)
        with self._conn() as cx:
            cx.execute(
                f"UPDATE speakers SET {clause} WHERE catalogue_id=?",
                [*updates.values(), catalogue_id],
            )

    def get_speaker(self, catalogue_id: str) -> Optional[SpeakerProfile]:
        with self._conn() as cx:
            row = cx.execute(
                "SELECT * FROM speakers WHERE catalogue_id=?", (catalogue_id,)
            ).fetchone()
        return _row_to_profile(row) if row else None

    def search_speakers(
        self,
        name: Optional[str] = None,
        affiliation: Optional[str] = None,
        role: Optional[str] = None,
    ) -> list[SpeakerProfile]:
        clauses, params = [], []
        if name:
            clauses.append("display_name LIKE ?")
            params.append(f"%{name}%")
        if affiliation:
            clauses.append("affiliation LIKE ?")
            params.append(f"%{affiliation}%")
        if role:
            clauses.append("role LIKE ?")
            params.append(f"%{role}%")
        where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
        with self._conn() as cx:
            rows = cx.execute(
                f"SELECT * FROM speakers {where} ORDER BY total_appearances DESC",
                params,
            ).fetchall()
        return [_row_to_profile(r) for r in rows]

    def top_speakers(self, limit: int = 20) -> list[dict]:
        """Most frequently appearing speakers across all sessions."""
        with self._conn() as cx:
            rows = cx.execute("""
                SELECT catalogue_id, display_name, affiliation, role,
                       total_appearances, total_speaking_time
                FROM speakers
                ORDER BY total_appearances DESC
                LIMIT ?
            """, (limit,)).fetchall()
        return [dict(r) for r in rows]

    # ── Appearance linking ─────────────────────────────────────────────────

    def link_appearance(
        self,
        catalogue_id: str,
        session_id: str,
        ephemeral_id: str,
        source_name: str = "",
        speaking_time: float = 0.0,
        turn_count: int = 0,
        avg_sentiment: Optional[float] = None,
    ) -> None:
        """
        Bind an ephemeral pyannote speaker ID to a named catalogue entry.
        Automatically pulls stats from the stored session JSON if not supplied.
        """
        # Auto-fill stats from the stored result if the caller didn't provide them
        if speaking_time == 0.0 and turn_count == 0:
            speaking_time, turn_count, avg_sentiment, source_name = (
                self._stats_from_session(session_id, ephemeral_id, source_name)
            )

        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as cx:
            # Skip if this ephemeral speaker is already linked to this catalogue
            # entry for this session (prevents double-counting on re-link).
            existing = cx.execute(
                "SELECT id FROM appearances WHERE catalogue_id=? AND session_id=? AND ephemeral_id=?",
                (catalogue_id, session_id, ephemeral_id),
            ).fetchone()
            if existing:
                log.info(
                    f"Appearance already recorded for {ephemeral_id} → {catalogue_id} "
                    f"in session {session_id}; skipping duplicate insert."
                )
                return

            cx.execute("""
                INSERT INTO appearances
                    (catalogue_id, session_id, ephemeral_id, source_name,
                     appeared_at, speaking_time, turn_count, avg_sentiment)
                VALUES (?,?,?,?,?,?,?,?)
            """, (catalogue_id, session_id, ephemeral_id, source_name,
                  now, speaking_time, turn_count, avg_sentiment))
            cx.execute("""
                UPDATE speakers SET
                    total_appearances   = total_appearances + 1,
                    total_speaking_time = total_speaking_time + ?,
                    last_seen           = ?
                WHERE catalogue_id = ?
            """, (speaking_time, now, catalogue_id))

        log.info(
            f"Linked {ephemeral_id} → {catalogue_id}  "
            f"({speaking_time:.1f}s, session {session_id})"
        )

    def get_appearances(self, catalogue_id: str) -> list[dict]:
        with self._conn() as cx:
            rows = cx.execute("""
                SELECT a.*, s.total_duration
                FROM appearances a
                LEFT JOIN sessions s USING (session_id)
                WHERE a.catalogue_id = ?
                ORDER BY a.appeared_at DESC
            """, (catalogue_id,)).fetchall()
        return [dict(r) for r in rows]

    def save_turn_override(
        self,
        session_id: str,
        turn_index: int,
        original_speaker: str,
        assigned_speaker: str,
        notes: str = "",
    ) -> None:
        """
        Persist a human correction for a single turn.
        Uses INSERT OR REPLACE so repeated edits just update the row.
        """
        now = datetime.now(timezone.utc).isoformat()
        with self._conn() as cx:
            cx.execute("""
                INSERT OR REPLACE INTO turn_overrides
                    (session_id, turn_index, original_speaker, assigned_speaker,
                     override_at, notes)
                VALUES (?,?,?,?,?,?)
            """, (session_id, turn_index, original_speaker, assigned_speaker, now, notes))

    def delete_turn_override(self, session_id: str, turn_index: int) -> None:
        """Remove a turn override, restoring the turn to its original speaker."""
        with self._conn() as cx:
            cx.execute(
                "DELETE FROM turn_overrides WHERE session_id=? AND turn_index=?",
                (session_id, turn_index),
            )

    def get_turn_overrides(self, session_id: str) -> dict[int, dict]:
        """
        Return all overrides for a session keyed by turn_index.
        Each value is: {original_speaker, assigned_speaker, override_at, notes}
        """
        with self._conn() as cx:
            rows = cx.execute("""
                SELECT turn_index, original_speaker, assigned_speaker,
                       override_at, notes
                FROM turn_overrides
                WHERE session_id = ?
            """, (session_id,)).fetchall()
        return {
            r["turn_index"]: {
                "original_speaker": r["original_speaker"],
                "assigned_speaker": r["assigned_speaker"],
                "override_at":      r["override_at"],
                "notes":            r["notes"] or "",
            }
            for r in rows
        }

    # ── Helpers ────────────────────────────────────────────────────────────

    def _next_id(self) -> str:
        with self._conn() as cx:
            n = cx.execute("SELECT COUNT(*) FROM speakers").fetchone()[0]
        return f"SPK-{n + 1:04d}"

    def _stats_from_session(
        self, session_id: str, ephemeral_id: str, source_name: str
    ) -> tuple[float, int, Optional[float], str]:
        with self._conn() as cx:
            row = cx.execute(
                "SELECT result_json, source_name FROM sessions WHERE session_id=?",
                (session_id,),
            ).fetchone()
        if not row:
            return 0.0, 0, None, source_name
        data = json.loads(row["result_json"])
        s = data.get("speaker_stats", {}).get(ephemeral_id, {})
        return (
            s.get("total_speaking_time", 0.0),
            s.get("turn_count", 0),
            s.get("avg_sentiment"),
            source_name or row["source_name"] or "",
        )


# ─── Row helper ───────────────────────────────────────────────────────────────

def _row_to_profile(row: sqlite3.Row) -> SpeakerProfile:
    return SpeakerProfile(
        catalogue_id=row["catalogue_id"],
        display_name=row["display_name"],
        affiliation=row["affiliation"],
        role=row["role"],
        notes=row["notes"],
        first_seen=row["first_seen"],
        last_seen=row["last_seen"],
        total_appearances=row["total_appearances"],
        total_speaking_time=row["total_speaking_time"],
    )